version: '3.8'

services:
  clickhouse:
    image: yandex/clickhouse-server
    container_name: clickhouse
    environment:
      - CLICKHOUSE_USER=testuser
      - CLICKHOUSE_PASSWORD=testpassword
    ports:
      - "8123:8123"
      - "9000:9000"

  postgres:
    image: postgres
    container_name: postgres
    environment:
    - POSTGRES_USER=testuser
    - POSTGRES_PASSWORD=testpassword
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

  nats:
    image: nats:latest
    ports:
      - "4222:4222"  
      - "8222:8222"  
      - "6222:6222"  